/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe.administrator;

import accountmanagement.database.DataBaseConnection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPAQ
 */
public class AdminBank extends javax.swing.JPanel {

    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;

    /**
     * Creates new form User
     */
    public AdminBank(String shopName) {
        this.shopName = shopName;
        getBankList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeCombo = new javax.swing.JComboBox();
        userType = new javax.swing.JLabel();
        userType1 = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        successLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FROM BANK", "MONEY IN(COMMISSION)", "SERVICES MONEY OUT", "EXPENDITURE MONEY OUT/ MONTHLY", "EXPENDITURE MONEY OUT/ YEARLY", "EXPENDITURE/BANK CHARGE", "PURCHASE", "PAY BACK", " " }));
        typeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboActionPerformed(evt);
            }
        });
        add(typeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 150, -1));

        userType.setText("Value");
        userType.setToolTipText("");
        add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 86, 20));

        userType1.setText("Type");
        userType1.setToolTipText("");
        add(userType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 86, 20));
        add(valueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 150, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 90, 30));

        successLabel.setForeground(new java.awt.Color(51, 204, 0));
        add(successLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 270, 20));

        warningLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 270, 20));

        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        successLabel.setText("");
        warningLabel.setText("");

        String type = typeCombo.getSelectedItem().toString();
        
        String value = valueTextField.getText();
        String valueEdited=null;
        
        switch (type) {
            case "FROM BANK":
                valueEdited = "FB_" + value;
                break;
            case "MONEY IN(COMMISSION)":
                valueEdited = "MI_" + value;
                break;
            case "SERVICES MONEY OUT":
                valueEdited = "SMO_" + value;
                break;
            case "EXPENDITURE MONEY OUT/ MONTHLY":
                valueEdited = "EM_" + value;
                break;
            case "EXPENDITURE MONEY OUT/ YEARLY":
                valueEdited = "EY_" + value;
                break;
            case "EXPENDITURE/BANK CHARGE":
                valueEdited = "EB_" + value;
                break;
            case "PURCHASE":
                valueEdited = "P_" + value;
                break;
            case "PAY BACK":
                valueEdited = "PB_" + value;
                break;
            default:
                System.out.println("no match");
        }

        if (!db.isColumnExist(shopName, "Bank", value)) {
            db.alterTabTable(shopName, "Bank", valueEdited);
            db.insertDetailTable(shopName, valueTextField.getText(), valueEdited, type, "BankDetail");
            getBankList();
            valueTextField.setText("");
            successLabel.setText("Expenditure added Successfully..");
        } else {
            valueTextField.setText("");
            warningLabel.setText("**Expenditure already exist.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboActionPerformed

    private void getBankList() {
//        ResultSet res = db.getDeatilTableValue(shopName, "BankDetail");
//        try {
//            while (res.next()) {
//                String item = res.getString("Item");
//                String type = res.getString("Type");
//                List<String> bankVal = new ArrayList();
//                bankVal.add(item);
//                bankVal.add(type);
//                bankIn.add(bankVal);
//            }
//        } catch (Exception e) {
//
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel successLabel;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JLabel userType;
    private javax.swing.JLabel userType1;
    private javax.swing.JTextField valueTextField;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
