/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe.administrator;

import accountmanagement.database.DataBaseConnection;
import accountmanagement.jframe.TillJframe;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author COMPAQ
 */
public class AdminExpenditure extends javax.swing.JPanel {
    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;
    /**
     * Creates new form AdminPurcharse
     */
    public AdminExpenditure(String shopName) {
        this.shopName = shopName;
        initComponents();
        getExpenditureList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Expenditure Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 31, 100, 22));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 114, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 90, -1));

        jScrollPane2.setBorder(null);

        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.alterTabTable(shopName, "Expenditure", jTextField1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void getExpenditureList(){
        ResultSetMetaData metadata = db.getTabColumns(shopName, "Expenditure");
        try {
            for (int i = 2; i <= metadata.getColumnCount(); i++) {
                String columnName = metadata.getColumnName(i);
                String tableModel[]={columnName};
                jList1.setListData(tableModel);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TillJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
