/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe.administrator;

import accountmanagement.database.DataBaseConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author COMPAQ
 */
public class AdminSale extends javax.swing.JPanel {

    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;

    /**
     * Creates new form AdminPurcharse
     *
     * @param shopName
     */
    public AdminSale(String shopName) {
        this.shopName = shopName;
        initComponents();
        getSalesList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        expenditureTypeTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        successLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Expenditure Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 31, 100, 22));
        add(expenditureTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 114, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 90, -1));

        jScrollPane2.setBorder(null);

        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 590));

        successLabel.setForeground(new java.awt.Color(51, 153, 0));
        add(successLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 220, 20));

        warningLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 220, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        successLabel.setText("");
        warningLabel.setText("");
             
        String value = expenditureTypeTextField.getText();
        String valueEdited = value.replaceAll("\\s+", "");
        
        if (!db.isColumnExist(shopName, "Sales", valueEdited)) {
            db.alterTabTable(shopName, "Sales", valueEdited);
            db.insertEPDetailTable(shopName, value, valueEdited, "SalesDetail");
            getSalesList();
            expenditureTypeTextField.setText("");
            successLabel.setText("Book Out added Successfully..");
        }else{
            expenditureTypeTextField.setText("");
            warningLabel.setText("**Book Out already exist.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void getSalesList() {
        ResultSet res = db.getDeatilTableValue(shopName, "SalesDetail");
        List<String> items = new ArrayList();

        try {
            while (res.next()) {
                String item = res.getString("Item");
                items.add(item);
            }
            jList1.setListData(items.toArray());
        } catch (SQLException ex) {
            Logger.getLogger(AdminPurcharse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField expenditureTypeTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel successLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
