/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe.administrator;

import accountmanagement.database.DataBaseConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author COMPAQ
 */
public class AdminProfit extends javax.swing.JPanel {

    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;

    /**
     * Creates new form User
     */
    public AdminProfit(String shopName) {
        this.shopName = shopName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        userType1 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        passwordTextField = new javax.swing.JPasswordField();
        confirmPasswordTextField = new javax.swing.JPasswordField();
        successLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        userType4 = new javax.swing.JLabel();
        userType5 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userType1.setText("Net Profit Percentage");
        userType1.setToolTipText("");
        add(userType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 180, 20));
        add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 90, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 90, 30));
        add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 90, -1));
        add(confirmPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 90, -1));

        successLabel.setForeground(new java.awt.Color(51, 204, 0));
        add(successLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 270, 20));

        warningLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 270, 20));

        userType4.setText("Purchase Percentage");
        userType4.setToolTipText("");
        add(userType4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 20));

        userType5.setText("Gross Profit Percentage");
        userType5.setToolTipText("");
        add(userType5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel successLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel userType1;
    private javax.swing.JLabel userType4;
    private javax.swing.JLabel userType5;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
