/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe.report.expenditure;

import accountmanagement.database.DataBaseConnection;
import accountmanagement.jframe.report.Blank;
import accountmanagement.jframe.report.Loading;
import com.google.common.collect.Lists;
import java.awt.CardLayout;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class ExpenditureTotalReport extends javax.swing.JPanel {

    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;
    private final String title;
    private final String tableName2;
    private final String tableName1;
    Map<String, String> colList11;
    String colList2;

    /**
     * Creates new form Till
     *
     * @param shopName
     * @param title
     * @param tableName1
     * @param tableName2
     * @param colList1
     * @param colList2
     */
    public ExpenditureTotalReport(String shopName, String title, String tableName1, String tableName2,
            Map<String, String> colList1, String colList2) {
        this.shopName = shopName;
        this.colList11 = colList1;
        this.title = title;
        this.colList2 = colList2;
        this.tableName1 = tableName1;
        this.tableName2 = tableName2;
        initComponents();
        this.jLabel4.setText(title.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooserFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jDateChooserTo = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        warningLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateChooserFrom.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jDateChooserFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 161, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("From Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 38, 80, 20));

        searchButton.setBackground(new java.awt.Color(0, 0, 102));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 90, 30));

        jDateChooserTo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jDateChooserTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 161, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("To Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 80, 20));

        warningLabel1.setForeground(new java.awt.Color(153, 0, 0));
        add(warningLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 430, 10));

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(getSize());
        jPanel1.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 560, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
//        jPanel1.removeAll();
//        jPanel1.add(new Loading());
//        CardLayout layout = (CardLayout) jPanel1.getLayout();
//        layout.next(jPanel1);

        Date currentDate = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if (jDateChooserFrom.getDate() == null) {
            jDateChooserFrom.setDate(currentDate);
        }
        if (jDateChooserTo.getDate() == null) {
            jDateChooserTo.setDate(currentDate);
        }
        String fromDate = sdf.format(jDateChooserFrom.getDate());
        String toDate = sdf.format(jDateChooserTo.getDate());

        if (fromDate.compareTo(toDate) < 0 || fromDate.compareTo(toDate) == 0) {
//            warningLabel1.setText("Loading..");
            List<Map<String, String>> data = new ArrayList();
            Map<String, Float[]> dataVal = new HashMap();

            ResultSet res = db.getNColValueTabTable(shopName, tableName1, Lists.newArrayList(colList11.keySet()), fromDate, toDate);
            ResultSet res1 = db.getOneColValueTabTable(shopName, tableName2, colList2, fromDate, toDate);

            int size = colList11.size() + 3;
            System.out.println(colList11 + " " + colList2 + " " + size);
            String description = "Date: " + fromDate + " - " + toDate;
            try {
                while (res.next()) {
                    Float total = 0f;
                    Float[] val = new Float[size];
                    int i = 0;
                    for (String col : colList11.keySet()) {
                        val[i] = res.getFloat(col);
                        total = total + res.getFloat(col);
                        i = i + 1;
                    }
                    val[i] = total;
                    System.out.println(i + " " + val[i]);
                    dataVal.put(res.getString("Date"), val);
                }

                while (res1.next()) {
                    if (dataVal.containsKey(res1.getString("Date"))) {
                        Float[] val = dataVal.get(res1.getString("Date"));
                        Float total = val[size - 3];
                        int i = colList11.size() + 1;

                        val[i] = res1.getFloat(colList2);
                        i = i + 1;

                        val[i] = res1.getFloat(colList2) - total;
                        dataVal.replace(res1.getString("Date"), val);

                    } else {
                        Float total = 0f;
                        Float[] val = new Float[size];
                        int i = colList11.size() + 1;

                        val[i] = res1.getFloat(colList2);
                        i = i + 1;

                        val[i] = res1.getFloat(colList2) - total;
                        dataVal.put(res1.getString("Date"), val);
                    }
                }

                for (String date : dataVal.keySet()) {
                    Float[] val = dataVal.get(date);
                    Map<String, String> map = new HashMap();
                    map.put("Date", date);
                    map.put("title", title.toUpperCase());
                    map.put("description", description);
                    int i = 0;
                    for (String col : colList11.keySet()) {
                        if (val[i] == null) {
                            map.put("Col" + (i + 1), "");
                        } else {
                            map.put("Col" + (i + 1), Float.toString(val[i]));
                        }
                        map.put("ColName" + (i + 1), colList11.get(col));
                        i = i + 1;
                    }

                    if (val[i] == null) {
                        map.put("Col" + (i + 1), "");
                    } else {
                        map.put("Col" + (i + 1), Float.toString(val[i]));
                    }
                    map.put("ColName" + (i + 1), "Total");
                    i = i + 1;

                    if (val[i] == null) {
                        map.put("Col" + (i + 1), "");
                    } else {
                        map.put("Col" + (i + 1), Float.toString(val[i]));
                    }
                    map.put("ColName" + (i + 1), tableName2);
                    i = i + 1;

                    if (val[i] == null) {
                        map.put("Col" + (i + 1), "");
                    } else {
                        map.put("Col" + (i + 1), Float.toString(val[i]));
                    }
                    map.put("ColName" + (i + 1), "Different");
                    data.add(map);
                }

                if (!data.isEmpty()) {
                    JRDataSource dataSource = new JRBeanCollectionDataSource(data);
                    InputStream sourceName = getClass().getResourceAsStream("/accountmanagement/jframe/report/Expenditure" + size + "Report.jrxml");

                    JasperReport jasperReport = JasperCompileManager.compileReport(sourceName);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, dataSource);

                    JasperViewer.viewReport(jasperPrint, false);
//                    JRViewer viewer = new JRViewer(jasperPrint);
//                    jPanel1.add(viewer);
//                    layout = (CardLayout) jPanel1.getLayout();
//                    layout.next(jPanel1);
//                    warningLabel1.setText("");
                } else {
//                    jPanel1.add(new Blank());
//                    layout = (CardLayout) jPanel1.getLayout();
//                    layout.next(jPanel1);
                    warningLabel1.setText("No record available within date " + fromDate + " - " + toDate);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ExpenditureTotalReport.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JRException ex) {
                Logger.getLogger(ExpenditureTotalReport.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            warningLabel1.setText("From Date should be earlier date");
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooserFrom;
    private com.toedter.calendar.JDateChooser jDateChooserTo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel warningLabel1;
    // End of variables declaration//GEN-END:variables
}
