/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe;

import accountmanagement.database.DataBaseConnection;
import accountmanagement.jframe.administrator.AdminBank;
import accountmanagement.jframe.administrator.AdminExpenditure;
import accountmanagement.jframe.administrator.AdminPetty;
import accountmanagement.jframe.administrator.AdminProfitNew;
import accountmanagement.jframe.administrator.AdminPurcharse;
import accountmanagement.jframe.administrator.CommissionAndService;
import accountmanagement.jframe.administrator.Staff;
import accountmanagement.jframe.administrator.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class Administrator extends javax.swing.JPanel {

    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;

    /**
     * Creates new form Administrator
     *
     * @param shopName
     */
    public Administrator(String shopName) {
        this.shopName = shopName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        staffButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        expenditureButton = new javax.swing.JButton();
        purcharseButton = new javax.swing.JButton();
        bankButton = new javax.swing.JButton();
        commissionButton = new javax.swing.JButton();
        pettyButton = new javax.swing.JButton();
        adminProfitButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        staffButton.setBackground(new java.awt.Color(0, 0, 51));
        staffButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        staffButton.setText("Staff");
        staffButton.setBorder(null);
        staffButton.setBorderPainted(false);
        staffButton.setContentAreaFilled(false);
        staffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffButton.setFocusPainted(false);
        staffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staffButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                staffButtonMouseHoverOut(evt);
            }
        });
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });

        userButton.setBackground(new java.awt.Color(0, 0, 51));
        userButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        userButton.setText("User");
        userButton.setBorder(null);
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton.setFocusPainted(false);
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButtonMouseHoverOut(evt);
            }
        });
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        expenditureButton.setBackground(new java.awt.Color(0, 0, 51));
        expenditureButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        expenditureButton.setText("Expenditure");
        expenditureButton.setBorder(null);
        expenditureButton.setBorderPainted(false);
        expenditureButton.setContentAreaFilled(false);
        expenditureButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expenditureButton.setFocusPainted(false);
        expenditureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                expenditureButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expenditureButtonMouseHoverOut(evt);
            }
        });
        expenditureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenditureButtonActionPerformed(evt);
            }
        });

        purcharseButton.setBackground(new java.awt.Color(0, 0, 51));
        purcharseButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        purcharseButton.setText("Purcharse");
        purcharseButton.setBorder(null);
        purcharseButton.setBorderPainted(false);
        purcharseButton.setContentAreaFilled(false);
        purcharseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purcharseButton.setFocusPainted(false);
        purcharseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purcharseButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purcharseButtonMouseHoverOut(evt);
            }
        });
        purcharseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purcharseButtonActionPerformed(evt);
            }
        });

        bankButton.setBackground(new java.awt.Color(0, 0, 51));
        bankButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        bankButton.setText("Bank");
        bankButton.setBorder(null);
        bankButton.setBorderPainted(false);
        bankButton.setContentAreaFilled(false);
        bankButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bankButton.setFocusPainted(false);
        bankButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bankButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bankButtonMouseHoverOut(evt);
            }
        });
        bankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankButtonActionPerformed(evt);
            }
        });

        commissionButton.setBackground(new java.awt.Color(0, 0, 51));
        commissionButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        commissionButton.setText("Commission & Service");
        commissionButton.setBorder(null);
        commissionButton.setBorderPainted(false);
        commissionButton.setContentAreaFilled(false);
        commissionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        commissionButton.setFocusPainted(false);
        commissionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commissionButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commissionButtonMouseHoverOut(evt);
            }
        });
        commissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commissionButtonActionPerformed(evt);
            }
        });

        pettyButton.setBackground(new java.awt.Color(0, 0, 51));
        pettyButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        pettyButton.setText("Petty");
        pettyButton.setBorder(null);
        pettyButton.setBorderPainted(false);
        pettyButton.setContentAreaFilled(false);
        pettyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pettyButton.setFocusPainted(false);
        pettyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pettyButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pettyButtonMouseHoverOut(evt);
            }
        });
        pettyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pettyButtonActionPerformed(evt);
            }
        });

        adminProfitButton.setBackground(new java.awt.Color(0, 0, 51));
        adminProfitButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        adminProfitButton.setText("Profit Percentage");
        adminProfitButton.setBorder(null);
        adminProfitButton.setBorderPainted(false);
        adminProfitButton.setContentAreaFilled(false);
        adminProfitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminProfitButton.setFocusPainted(false);
        adminProfitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminProfitButtonMouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminProfitButtonMouseHoverOut(evt);
            }
        });
        adminProfitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminProfitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expenditureButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purcharseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bankButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commissionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pettyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminProfitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purcharseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenditureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pettyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminProfitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void staffButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseHover
        staffButton.setForeground(Color.red);
    }//GEN-LAST:event_staffButtonMouseHover

    private void staffButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseHoverOut
        staffButton.setForeground(Color.black);
    }//GEN-LAST:event_staffButtonMouseHoverOut

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        jPanel1.add("Staff", new Staff(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_staffButtonActionPerformed

    private void userButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseHover
        userButton.setForeground(Color.red);
    }//GEN-LAST:event_userButtonMouseHover

    private void userButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseHoverOut
        userButton.setForeground(Color.black);
    }//GEN-LAST:event_userButtonMouseHoverOut

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        jPanel1.add("User", new User(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_userButtonActionPerformed

    private void expenditureButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expenditureButtonMouseHover
        expenditureButton.setForeground(Color.red);
    }//GEN-LAST:event_expenditureButtonMouseHover

    private void expenditureButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expenditureButtonMouseHoverOut
        expenditureButton.setForeground(Color.black);
    }//GEN-LAST:event_expenditureButtonMouseHoverOut

    private void expenditureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenditureButtonActionPerformed
        jPanel1.add("AdminExpenditure", new AdminExpenditure(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_expenditureButtonActionPerformed

    private void purcharseButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purcharseButtonMouseHover
        purcharseButton.setForeground(Color.red);
    }//GEN-LAST:event_purcharseButtonMouseHover

    private void purcharseButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purcharseButtonMouseHoverOut
        purcharseButton.setForeground(Color.black);
    }//GEN-LAST:event_purcharseButtonMouseHoverOut

    private void purcharseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purcharseButtonActionPerformed
        jPanel1.add("AdminPurcharse", new AdminPurcharse(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_purcharseButtonActionPerformed

    private void bankButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankButtonMouseHover
        // TODO add your handling code here:
    }//GEN-LAST:event_bankButtonMouseHover

    private void bankButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankButtonMouseHoverOut
        // TODO add your handling code here:
    }//GEN-LAST:event_bankButtonMouseHoverOut

    private void bankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankButtonActionPerformed
        jPanel1.add("AdminBank", new AdminBank(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_bankButtonActionPerformed

    private void commissionButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commissionButtonMouseHover
        // TODO add your handling code here:
    }//GEN-LAST:event_commissionButtonMouseHover

    private void commissionButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commissionButtonMouseHoverOut
        // TODO add your handling code here:
    }//GEN-LAST:event_commissionButtonMouseHoverOut

    private void commissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commissionButtonActionPerformed
        jPanel1.add("CommissionAndService", new CommissionAndService(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_commissionButtonActionPerformed

    private void pettyButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pettyButtonMouseHover
        // TODO add your handling code here:
    }//GEN-LAST:event_pettyButtonMouseHover

    private void pettyButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pettyButtonMouseHoverOut
        // TODO add your handling code here:
    }//GEN-LAST:event_pettyButtonMouseHoverOut

    private void pettyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pettyButtonActionPerformed
        jPanel1.add("AdminPetty", new AdminPetty(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_pettyButtonActionPerformed

    private void adminProfitButtonMouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminProfitButtonMouseHover
        // TODO add your handling code here:
    }//GEN-LAST:event_adminProfitButtonMouseHover

    private void adminProfitButtonMouseHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminProfitButtonMouseHoverOut
        // TODO add your handling code here:
    }//GEN-LAST:event_adminProfitButtonMouseHoverOut

    private void adminProfitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminProfitButtonActionPerformed
        jPanel1.add("AdminProfitNew", new AdminProfitNew(shopName));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1);
    }//GEN-LAST:event_adminProfitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminProfitButton;
    private javax.swing.JButton bankButton;
    private javax.swing.JButton commissionButton;
    private javax.swing.JButton expenditureButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pettyButton;
    private javax.swing.JButton purcharseButton;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
