/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe;

import accountmanagement.database.DataBaseConnection;

/**
 *
 * @author acer
 */
public class Bank extends javax.swing.JPanel {

    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;
    /**
     * Creates new form Till
     */
    public Bank(String shopName) {
        this.shopName = shopName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        saveBankButton = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTextField49 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(746, 960));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 161, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 20));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("0");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 96, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("From Bank");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 167, 20));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setText("0");
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 96, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Cash Plus");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("NATWEST");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 20));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setText("0");
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 96, 20));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Money In");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 167, 20));

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField13.setText("0");
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 96, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Note Machine");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 20));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Pay Zone");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 20));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("Reset");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 90, 30));

        saveBankButton.setBackground(new java.awt.Color(0, 0, 102));
        saveBankButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        saveBankButton.setForeground(new java.awt.Color(255, 255, 255));
        saveBankButton.setText("Save");
        saveBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBankButtonActionPerformed(evt);
            }
        });
        add(saveBankButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 90, 30));

        jTextField22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField22.setText("0");
        add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 96, 20));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Eleven Card");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, 20));

        jTextField23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField23.setText("0");
        add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 96, 20));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Milk Vouture");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, 20));

        jTextField24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField24.setText("0");
        add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 96, 20));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setText("Services Money Out");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 167, 20));

        jTextField25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField25.setText("0");
        add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 96, 20));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Pay Zone");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, 20));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Pay Point");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 130, 20));

        jTextField26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField26.setText("0");
        add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 96, 20));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Oyster");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 120, 20));

        jTextField27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField27.setText("0");
        add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 96, 20));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Camlot");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 120, 20));

        jTextField28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField28.setText("0");
        add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 96, 20));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel32.setText("Expenditure Money Out (Monthly)");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 290, 20));

        jTextField29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField29.setText("0");
        add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 96, 20));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("BT");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 120, 20));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("Capital Gains");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 130, 20));

        jTextField30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField30.setText("0");
        add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 96, 20));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("NEST");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 120, 20));

        jTextField31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField31.setText("0");
        add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 96, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Rent");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, 20));

        jTextField32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField32.setText("0");
        add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 96, 20));

        jTextField33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField33.setText("0");
        add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 96, 20));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("Alarm");
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 120, 20));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("Water");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 130, 20));

        jTextField34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField34.setText("0");
        add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 96, 20));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setText("Electric");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 120, 20));

        jTextField35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField35.setText("0");
        add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 96, 20));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setText("Toilet Block");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 120, 20));

        jTextField36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField36.setText("0");
        add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 96, 20));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setText("Salary Mike");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 120, 20));

        jTextField37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField37.setText("0");
        add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 96, 20));

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("Salary Sathees");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 120, 20));

        jTextField38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField38.setText("0");
        add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 96, 20));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel43.setText("Expenditure Money Out (Yearly)");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 290, 20));

        jTextField39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField39.setText("0");
        add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 96, 20));

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setText("BIFFA");
        add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 120, 20));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("Shop Insurance");
        add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 130, 20));

        jTextField40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField40.setText("0");
        add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 96, 20));

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("BUIL / INSU");
        add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 120, 20));

        jTextField41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField41.setText("0");
        add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 96, 20));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setText("Off / Fee");
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 120, 20));

        jTextField42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField42.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField42.setText("0");
        add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 96, 20));

        jTextField43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField43.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField43.setText("0");
        add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 96, 20));

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel48.setText("Expenditure / Bank charge");
        add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 290, 20));

        jTextField44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField44.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField44.setText("0");
        add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 96, 20));

        jTextField45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField45.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField45.setText("0");
        add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 96, 20));

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setText("Bank Charge");
        add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 120, 20));

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setText("Eleven Charge");
        add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 130, 20));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel51.setText("Card Machine");
        add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 120, 20));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setText("PayZone Rental");
        add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 120, 20));

        jTextField46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField46.setText("0");
        add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 96, 20));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel53.setText("Purchase");
        add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 167, 20));

        jTextField47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField47.setText("0");
        add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 96, 20));

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel54.setText("NI");
        add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 120, 20));

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setText("Cost Cutter");
        add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 130, 20));

        jTextField48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField48.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField48.setText("0");
        add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 96, 20));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setText("BestWay");
        add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 120, 20));

        jTextField49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField49.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField49.setText("0");
        add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 96, 20));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel57.setText("Pay Back");
        add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 167, 20));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel58.setText("Borrow Money");
        add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void saveBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBankButtonActionPerformed
        db.addItemToBank(shopName, shopName);
    }//GEN-LAST:event_saveBankButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton saveBankButton;
    // End of variables declaration//GEN-END:variables
}
