/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanagement.jframe;

import accountmanagement.database.DataBaseConnection;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class Purcharse extends javax.swing.JPanel {

    DataBaseConnection db = new DataBaseConnection();
    private final String shopName;
    private static HashMap<String, JTextField> listOfTextFields = new HashMap<>();
    private boolean isUpdate = false;

    /**
     * Creates new form Till
     *
     * @param shopName
     */
    public Purcharse(String shopName) {
        this.shopName = shopName;
        initComponents();
        populatePurchase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        successLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 38, 161, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 38, 167, 20));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 90, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 90, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));

        successLabel.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 687, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        successLabel.setText("");
        successLabel.setText("");
        boolean canSave = true;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if (jDateChooser1.getDate() != null) {
            HashMap<String, Float> purchaseValues = new HashMap();
            float total = 0;
            for (String name : listOfTextFields.keySet()) {
                try {
                    Float val = listOfTextFields.get(name).getText()== null || listOfTextFields.get(name).getText().isEmpty() ?
                            0 : Float.parseFloat(listOfTextFields.get(name).getText());

                    purchaseValues.put(name, val);
                    total = total + val;
                } catch (java.lang.NumberFormatException e) {
                    successLabel.setText("**All Values are mandatory and should be decimal");
//                    listOfTextFields.get(name).setBorder(BorderFactory.createLineBorder(Color.RED, 2));
                    canSave = false;
                    break;
                } catch (Exception e) {
                    successLabel.setText("**Error in updating Purchase");
                    successLabel.setForeground(Color.red);
                    canSave = false;
                }
            }
            purchaseValues.put("Total", total);
            System.out.println(purchaseValues.toString());
            
            if (canSave) {
                if (!isUpdate) {
                    db.insertValuesTabTable(shopName, "Purchase", sdf.format(jDateChooser1.getDate()), purchaseValues);
                    successLabel.setText("Purcharse added successfully..");
                    successLabel.setForeground(Color.green);
                    resetText();
                } else {
                    db.updateValuesTabTable(shopName, "Purchase", sdf.format(jDateChooser1.getDate()), purchaseValues);
                    successLabel.setText("Expenditure Updated successfully..");
                    successLabel.setForeground(Color.green);
                    resetText();
                }
            }

        } else {
            successLabel.setText("**Date should be selected");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        successLabel.setText("");
        resetText();
        getValues();
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void getValues() {
        if (jDateChooser1.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            if (db.isDateExist(shopName, "Purchase", sdf.format(jDateChooser1.getDate()))) {
                isUpdate = true;
                try {
                    ResultSet res = db.getExistingValueTabTable(shopName, "Purchase", sdf.format(jDateChooser1.getDate()));

                    for (String col : listOfTextFields.keySet()) {
                        JTextField text = listOfTextFields.get(col);
                        text.setText(res.getString(col));
                    }

                } catch (Exception ex) {
                    Logger.getLogger(Till.class.getName()).log(Level.SEVERE, null, ex);
                    successLabel.setText("**Error getting Purchase Detail");
                    successLabel.setForeground(Color.red);
                }

            }
        }
    }

    private void resetText() {
        for (String name : listOfTextFields.keySet()) {
            listOfTextFields.get(name).setText("");
        }
    }

    private void populatePurchase() {
        ResultSet res = db.getDeatilTableValue(shopName, "PurchaseDetail");
        try {
            int i = 1;
            while (res.next()) {
                String item = res.getString("Item");
                String name = res.getString("Name");
                if (!item.equalsIgnoreCase("Total")) {
                    JLabel label = new JLabel(item);
                    label.setFont(new java.awt.Font("Tahoma", 0, 12));
                    label.setBounds(20, 30 * i, 130, 20);

                    JTextField textField = new JTextField();
                    textField.setFont(new java.awt.Font("Tahoma", 0, 12));
                    textField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                    textField.setText("");
                    textField.setBounds(220, 30 * i, 96, 25);

                    jPanel1.add(label);
                    jPanel1.add(textField);
                    listOfTextFields.put(name, textField);
                    i = i + 1;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Purcharse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel successLabel;
    // End of variables declaration//GEN-END:variables
}
